type: object
properties:
  id:
      type: string
      format: uuid
  issuesToCombine:
    type: integer
  pattern:
    oneOf: 
     # -  $ref: CombinationPatternDay.yaml
     # -  $ref: CombinationPatternDayMonth.yaml
     # -  $ref: CombinationPatternDayWeek.yaml
     # -  $ref: CombinationPatternDayWeekday.yaml
     # -  $ref: CombinationPatternDayWeekMonth.yaml
      -  $ref: CombinationPatternIssue.yaml
      -  $ref: CombinationPatternIssueMonth.yaml
      -  $ref: CombinationPatternIssueWeek.yaml
      -  $ref: CombinationPatternIssueWeekMonth.yaml
     # -  $ref: CombinationPatternMonth.yaml
     # -  $ref: CombinationPatternWeek.yaml
     # -  $ref: CombinationPatternWeekMonth.yaml
  patternType:
    $ref: CombinationPatternType.yaml
  timeUnit:
    $ref: CombinationTimeUnit.yaml