type: object
properties:
  value:
    type: string
    enum: ["day", "week", "month_date", "month_weekday", "year_date", "year_weekday", "year_month_weekday"]
  id:
    type: string
    format: uuid
  label:
    type: string