grails:
  gorm:
    multiTenancy:
      mode: SCHEMA
      tenantResolverClass: org.grails.datastore.mapping.multitenancy.resolvers.SystemPropertyTenantResolver # System prop of gorm.tenantId 
  plugin:
    databasemigration:
      updateOnStart: true
      updateOnStartFileName: module-tenant-changelog.groovy