##
# This config file connects to the postgres install mapped by the vagrant file in the project root.
# Use the flag '-Dgrails.env=vagrant-db' when running
##
---
dataSource:
  dbCreate: none
  url: "jdbc:postgresql://${db.host:localhost}:${db.port:54321}/${db.database:okapi_modules}" # Port 54321 forwarded so as not to clash.
  username: "${db.username:folio_admin}"
  password: "${db.password:folio_admin}"
  driverClassName: org.postgresql.Driver
  dialect: com.k_int.hibernate.dialects.postgres.KIPostgres94Dialect
  schemaHandler: com.k_int.okapi.OkapiSchemaHandler
  properties:
      jmxEnabled: false
      initialSize: 5
      maxActive: 50
      minIdle: 5
      maxIdle: 25
      maxWait: 10000
      maxAge: 600000
      timeBetweenEvictionRunsMillis: 5000
      minEvictableIdleTimeMillis: 60000
      validationQuery: SELECT 1
      validationInterval: 30000
      testOnBorrow: true
      testWhileIdle: true
      testOnReturn: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      abandonWhenPercentageFull: 50
      jdbcInterceptors: ConnectionState
      defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
server:
  host: localhost
  port: 8079
 