##
# This config file connects to the postgres install from a rancher desktop instance.
# Use the flag '-Dgrails.env=rancher-desktop-db' when running
##

dataSource:
  dbCreate: none
  url: "jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.database:okapi_modules_test}" # Port 5432 forwarded so as not to clash.
  username: postgres
  password: pa55w0rd
  driverClassName: org.postgresql.Driver
  dialect: com.k_int.hibernate.dialects.postgres.KIPostgres94Dialect
  schemaHandler: com.k_int.okapi.OkapiSchemaHandler
  logSql: false
  properties:
      jmxEnabled: false
      maximumPoolSize: ${db.maxpoolsize:10}
      transactionIsolation: TRANSACTION_READ_COMMITTED
  hibernate:
    enable_lazy_load_no_trans: true

okapi: 
  service:
    host: localhost
    port: 30100
logging:
  config: classpath:logback-development.xml



#    register: true
#    deploy: true
        
      
