##
# This config file connects to the postgres install mapped by the vagrant file in the project root.
# Use the flag '-Dgrails.env=vagrant-db' when running
##
---
dataSource:
  dbCreate: none
  url: "jdbc:postgresql://${db.host:localhost}:${db.port:54321}/${db.database:okapi_modules}" # Port 54321 forwarded so as not to clash.
  username: "${db.username:folio_admin}"
  password: "${db.password:folio_admin}"
  driverClassName: org.postgresql.Driver
  dialect: com.k_int.hibernate.dialects.postgres.KIPostgres94Dialect
  schemaHandler: com.k_int.okapi.OkapiSchemaHandler
  properties:
    jmxEnabled: false
    maximumPoolSize: ${db.maxpoolsize:10}
    transactionIsolation: TRANSACTION_READ_COMMITTED
---
server:
  host: localhost
  port: 8076
logging:
  config: classpath:logback-development.xml
hibernate:
  enable_lazy_load_no_trans: true
 