apiVersion: apps/v1
kind: Deployment
metadata:
  name: $MOD_DEPLOY_AS
  labels:
    app: $MOD_DEPLOY_AS
    module: "mod-serials-management"
    folio_role: "backend-module"
  namespace: "$TARGET_NAMESPACE"
spec:
  selector:
    matchLabels:
      app: $MOD_DEPLOY_AS
  replicas: 1
  template:
    metadata:
      labels:
        app: $MOD_DEPLOY_AS
        module: "mod-serials-management"
        folio_role: "backend-module"
    spec:
      containers:
        - name: $MOD_DEPLOY_AS
          image: docker.libsdev.k-int.com/$MOD_IMAGE
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: folio-db-connect
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OKAPI_SERVICE_PORT
              value: "9130"
            - name: OKAPI_SERVICE_HOST
              value: "okapi"
            - name: JAVA_OPTIONS
              value: "-server -XX:+UseContainerSupport -XX:MaxRAMPercentage=55.0 -XX:+PrintFlagsFinal"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 768Mi
            limits:
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: $MOD_DEPLOY_AS
  namespace: "$TARGET_NAMESPACE"
spec:
  type: "ClusterIP"
  selector:
    app: $MOD_DEPLOY_AS
  ports:
    - port: 8080
