#! /bin/sh
USAGE="Usage: `basename $0` [-h] [-u username] [-p password] [-t tenant]"

# We may not be run from this directory
SCRIPT_DIRECTORY=`dirname "$0"`
TENANT="diku"
UN="diku_admin"
PW="admin"

if [ -f .okapirc ]; then
  . ./.okapirc
elif [ -f $HOME/.okapirc ]; then
  . $HOME/.okapirc
fi

# Parse command line options.
while getopts "h:u:p:t:" OPT; do
  case "$OPT" in
    h)
      echo $USAGE
      exit 0
      ;;
    u)
      UN=$OPTARG
      ;;
    p)
      PW=$OPTARG
      ;;
    t)
      TENANT=$OPTARG
      ;;
    \?)
      # getopts issues an error message
      echo $USAGE >&2
      exit 1
      ;;
  esac
done

# Remove the options we parsed above.
shift `expr $OPTIND - 1`

AUTH_TOKEN=$(curl -sSL -X POST -H 'accept: application/json' -H 'Content-type: application/json' \
    -H "X-Okapi-Tenant: $TENANT" --connect-timeout 5 --max-time 30 -d "{ \"username\":\"${UN}\", \"password\": \"${PW}\" }" \
    "${OKAPI_URL}/authn/login" | jq -rc '.okapiToken' | sed 's/.*: *//' | xargs)

echo "$AUTH_TOKEN"
exit 0