name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  run-openapi-pipeline:
    uses: k-int/github-actions/.github/workflows/folio-api-pipeline.yml@main
    secrets:
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}