name: Gradle Central Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gradle:
    uses: folio-org/.github/.github/workflows/gradle.yml@v1
    # Only handle push events from the main branch or tags, to decrease PR noise
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push' || github.ref_type == 'tag'
    secrets: inherit
    with:
      artifact-id: mod-serials-management
      docker-label-documentation: https://github.com/folio-org/mod-serials-management/tree/master/docs
